command="cd C:\/Users\/User\/Cleanworkspace\/$1";
echo "command: $command";
$command;
command1="git init" ;
echo "Command1: $command1";
$command1;
command2=$(echo -e 'target/\n.classpath\n.gitignore\n.project\n.settings/'  >> .gitignore ) ; 
$command2;
command3="git add --all" ; 
echo "command3: $command3";
$command3;
command4=$(git commit -m 'Java 8 $1'); 
$command4;
command5="git remote add origin git@github.com:userInterview/$2.git" ; 
echo "command5: $command5";
$command5;
command6="git branch java8$1";
echo "command6: $command6";
$command6;
command7="git checkout java8$1" ; 
echo "command7: $command7";
$command7;
eval "$(ssh-agent)" ;
ssh-add C:/Users/User/.ssh/winkeyloizv2;
command10="git push --set-upstream origin java8$1";
echo "Command10: $command10";
$command10;